"""added session2

Revision ID: 0c8bf231f1b1
Revises: 60ee73b7bdde
Create Date: 2022-07-16 13:37:45.376026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0c8bf231f1b1"
down_revision = "60ee73b7bdde"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
