"""init migration

Revision ID: c7aec211af22
Revises: 8a79cc33d863
Create Date: 2022-07-26 10:48:00.142806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c7aec211af22"
down_revision = "8a79cc33d863"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("devices", "manageable", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("devices", "manageable", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
