"""added device columns

Revision ID: c45d5b28a2ab
Revises: 1d9d7413feea
Create Date: 2022-07-17 22:00:35.552918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c45d5b28a2ab"
down_revision = "1d9d7413feea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("devices", sa.Column("fqdn", sa.String(length=255), nullable=True))
    op.add_column(
        "devices", sa.Column("username", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "devices", sa.Column("hashed_password", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("devices", "hashed_password")
    op.drop_column("devices", "username")
    op.drop_column("devices", "fqdn")
    # ### end Alembic commands ###
