"""added additional fields to device model

Revision ID: 193209bac4e9
Revises: 1fbe39480763
Create Date: 2022-07-16 20:46:33.858286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "193209bac4e9"
down_revision = "1fbe39480763"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("devices", sa.Column("site", sa.String(length=255), nullable=True))
    op.add_column("devices", sa.Column("vendor", sa.String(length=255), nullable=True))
    op.add_column("devices", sa.Column("model", sa.String(length=255), nullable=True))
    op.add_column(
        "devices", sa.Column("operating_system", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "devices", sa.Column("os_version", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("devices", "os_version")
    op.drop_column("devices", "operating_system")
    op.drop_column("devices", "model")
    op.drop_column("devices", "vendor")
    op.drop_column("devices", "site")
    # ### end Alembic commands ###
