"""added manageable column2

Revision ID: ac177b4eb4af
Revises: 25431bb06511
Create Date: 2022-07-22 17:58:58.653635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ac177b4eb4af"
down_revision = "25431bb06511"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("devices", sa.Column("manageable", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("devices", "manageable")
    # ### end Alembic commands ###
