"""updated default date values

Revision ID: 4eb1e5088763
Revises: a42d98bdc912
Create Date: 2022-07-25 14:08:53.134364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4eb1e5088763"
down_revision = "a42d98bdc912"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
