"""base mixin created

Revision ID: 48eb0e97d877
Revises: 0e7ad884be1e
Create Date: 2022-07-25 13:49:56.567103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "48eb0e97d877"
down_revision = "0e7ad884be1e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "devices",
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "devices",
        sa.Column(
            "updated", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "updated", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "updated")
    op.drop_column("users", "created")
    op.drop_column("devices", "updated")
    op.drop_column("devices", "created")
    # ### end Alembic commands ###
