"""modified nullable fields in device table v2

Revision ID: 1d9d7413feea
Revises: f1f3879e2520
Create Date: 2022-07-16 21:30:08.657975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1d9d7413feea"
down_revision = "f1f3879e2520"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
