"""base mixin created

Revision ID: a42d98bdc912
Revises: 48eb0e97d877
Create Date: 2022-07-25 13:50:12.550716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a42d98bdc912"
down_revision = "48eb0e97d877"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
