"""message

Revision ID: df139a2fb305
Revises: 9af6800fc315
Create Date: 2022-07-13 01:34:55.308618

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = 'df139a2fb305'
down_revision = '9af6800fc315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('username', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('hashed_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'hashed_password')
    op.drop_column('devices', 'username')
    # ### end Alembic commands ###
