"""default uuid

Revision ID: e6f06b76ef39
Revises: 5fcba80a7f71
Create Date: 2022-07-15 00:56:02.772683

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = 'e6f06b76ef39'
down_revision = '5fcba80a7f71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
